discord:
  token: DISCORD_BOT_TOKEN
  enabled: false

  links:
    - alias: Strona internetowa
      url: https://flyingoctopus.pl
    - alias: Facebook
      url: https://www.facebook.com/FO.flyingoctopus/
    - alias: Itch.io
      url: https://flyingoctopus.itch.io/
    - alias: Wiki
      url: https://wiki.flyingoctopus.pl/bin/view/Main/
    - alias: Asterielle
      url: http://elf-vs-dwarves.pl/
    - alias: Discord
      url: https://discord.com/invite/Q2DuSNY
  admins:
    - dyedMagenta#6609


trello:
  token: foo
  key: foo

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost/discorddb
    username: octopusdb
    password: octopusdb
  flyway:
    url: jdbc:postgresql://localhost/discorddb
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
