discord:
  token: DISCORD_BOT_TOKEN
  enabled: false

  links:
    '[Strona internetowa]': https://flyingoctopus.pl
    Facebook: https://www.facebook.com/FO.flyingoctopus/
    Itch.io: https://flyingoctopus.itch.io/
    Wiki: https://wiki.flyingoctopus.pl/bin/view/Main/
    Asterielle: http://elf-vs-dwarves.pl/
    Discord: https://discord.com/invite/Q2DuSNY

trello:
  token: foo

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost/discorddb
    username: octopusdb
    password: octopusdb
  flyway:
    url: jdbc:postgresql://localhost/discorddb
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
